export const mylabFr = {
  title: "MyLab — Application Cross-Platform & Gestion des Talents",
  shortDesc:
    "Application web et mobile cross-platform de centralisation des compétences, TJM et disponibilités — Flutter 3, Dart, Supabase, BLoC, Azure DevOps.",
  definition:
    "**MyLab** est une application d'entreprise cross-platform (Web, Android, iOS) stratégique développée au sein d'Orange Business. Elle a été créée pour répondre aux besoins des commerciaux, managers et chefs de projet en remplaçant un ancien fichier Excel obsolète et rigide par une solution moderne permettant d'actualiser et de cartographier en temps réel les compétences techniques, les soft skills, les TJM (Taux Journaliers Moyens) et les disponibilités des développeurs du service.",
  framing:
    "J'ai contribué au développement de MyLab dans le cadre de mon **Titre Professionnel CDA (Bac +3/4)** chez Orange Business. Le projet s'appuie sur le framework **Flutter 3 / Dart** pour garantir une base de code unique multi-plateforme, couplé à la base de données relationnelle **Supabase (PostgreSQL BaaS)** et à une architecture découpée en deux dépôts distincts (`Front-end` et `Data/Domain`) suivant la **Clean Architecture**. Mes enjeux principaux ont couvert l'audit des besoins métiers, la structuration des composants réactifs, la gouvernance des données sous Supabase et la collaboration agile collective au sein d'une équipe de développeurs pairs sous la méthodologie **SCRUM**.",
  action:
    "En tant que développeur participant au projet au sein d'un collectif de pairs, mon travail s'est articulé autour de 4 chantiers majeurs : l'audit des besoins avec conciliation des attentes métiers et la structuration du Front-End (BLoC pattern, AutoRoute, ResponsiveWidget) ; la gouvernance des données et la sécurité au niveau ligne sous Supabase (PostgreSQL, RLS SQL, Storage) ; la contribution active à l'organisation agile collective face aux fluctuations d'effectif avec animation de sessions de partage de connaissances entre pairs ; et la mise en place des pipelines CI/CD sous Azure DevOps pour les versions Web, Android et iOS.",
  results:
    "J'ai participé activement au développement collectif de l'application **MyLab** que j'ai présentée avec succès devant le jury pour l'obtention de mon diplôme **CDA (Bac +3/4)**. La solution a permis d'éliminer la dette opérationnelle d'Excel, d'offrir une visibilité instantanée sur les talents d'Orange Business et d'automatiser la chaîne de build multi-plateformes sous Azure DevOps.",
  critical:
    "Cette expérience a été une étape clé dans ma progression d'ingénieur logiciel. Elle a démontré ma capacité à maîtriser des technologies modernes (Flutter, Dart, Supabase, Azure DevOps), à faire preuve d'**écoute active auprès des utilisateurs métiers**, d'esprit d'entraide et d'auto-organisation au sein d'une équipe collective de développeurs.",

  tabs: {
    project: {
      label: "Le Projet",
      title: "Vue d'ensemble, Contexte d'Entreprise & Enjeux Métiers",
      badge: "Contexte Applicatif & Transformation Digitale",
      content:
        "### Le Contexte d'Entreprise chez Orange Business\nAu sein d'Orange Business Services (OBS), filiale du groupe Orange regroupant plus de 30 000 collaborateurs B2B et 9 700 experts digitaux mondialement répartis, j'ai rejoint une entité fonctionnant comme une ESN interne. Notre service regroupe 50 développeurs, 6 chefs de projet (répartis sur les pôles Web, Mobile et Data), 6 commerciaux, des managers et une RH de proximité.\n\n### Le Problème Métier : L'Obsolescence du Fichier Excel\nAvant le développement de **MyLab**, la cartographie des compétences et le suivi des disponibilités des développeurs de notre agence étaient gérés manuellement via un fichier Excel partagé. Cet outil présentait des limites opérationnelles critiques :\n- **Obsolescence des données en temps réel** : Le fichier n'était mis à jour que très rarement, générant des décalages d'information néfastes lors de l'attribution des missions.\n- **Frictions entre pôles** : Les commerciaux déploraient le manque de réactivité pour trouver le bon profil au bon TJM, tandis que les développeurs se sentaient mal valorisés dans leurs compétences réelles et soft skills.\n- **Absence d'ergonomie mobile** : Impossible pour un commercial ou un manager en déplacement d'accéder rapidement aux profils depuis son smartphone.\n\n### Les Objectifs de l'Application MyLab\n- **Autonomie des Développeurs** : Permettre à chaque développeur d'actualiser facilement ses compétences (technologies, niveaux de 1 à 5, soft skills) et de déclarer sa disponibilité.\n- **Centralisation & Visibilité Décisionnelle** : Offrir aux commerciaux et chefs de projet une plateforme fluide pour consulter les fiches profils, filtrer par critères métiers et télécharger les CVs PDF en un clic.\n- **Expérience Cross-Platform Unique** : Proposer une application accessible sur Web bureau et smartphones Android/iOS à partir d'une base de code unique sous Flutter 3.\n\n### Stack Technique Globale\n- **Front-End & Mobile** : Flutter 3, Dart, BLoC Pattern, AutoRoute, composants réactifs multi-écrans.\n- **Back-End & Base de Données** : Supabase BaaS (PostgreSQL, APIs RESTful auto-générées, Supabase Auth, Supabase Storage).\n- **Architecture** : Découpage en 2 dépôts Git distincts (`Front-end` et `Data/Domain`) suivant la **Clean / Hexagonal Architecture**.\n- **DevOps & CI/CD** : Azure DevOps Pipelines (automatisation des builds Web, packages Android et iOS TestFlight).\n\n### Mon Rôle & Implication dans l'Équipe Agile\nJ'ai travaillé sur ce projet en tant que **développeur participant** dans le cadre de mon alternance pour le **Titre Pro CDA (Bac +3/4)** chez Orange Business. En travail collectif au sein de l'équipe de développeurs en inter-contrat et en lien avec notre chef de projet, j'ai participé activement à l'ensemble du cycle de développement selon la méthodologie **SCRUM** (sprints de 2 semaines, réunions Daily à 9h30, suivi des tickets sous Azure Boards).",
    },

    situation1: {
      label: "1. Audit, Figma & Clean Arch BLoC",
      title: "Situation 1 — Audit des Besoins, Médiation Métier & Architecture Clean BLoC",
      badge: "Ingénierie des Besoins & Communication Interpersonnelle",
      framing:
        "Avant de concevoir l'architecture technique, mon premier travail a été de mener une démarche d'**écoute active** auprès des différents corps de métier d'Orange Business pour recueillir leurs besoins précis.",
      action:
        "J'ai participé aux échanges et synthétisé les attentes de chaque partie prenante :\n- **Les Commerciaux** : Souhaitaient faire ressortir les 3 principaux soft skills (validés par le manager référent pour garantir l'objectivité), afficher le TJM (Taux Journalier Moyen) idéal et minimum, et disposer d'un lien vers le profil LinkedIn à jour.\n- **Les Talent Acquisition Specialists** : Demandaient d'intégrer l'historique détaillé des projets (stack technique, durée, taille d'équipe et statut détaché chez le client vs sur le plateau).\n- **Les Chefs de Projet & Managers** : Avaient besoin d'un workflow clair de validation des niveaux de compétence et d'un filtre d'attribution des ressources en inter-contrat.\n- **Les Développeurs** : Réclamaient une interface ultra-rapide et valorisante, ne nécessitant que quelques clics pour actualiser leur profil.\n\n### Conception Graphique sur Figma & Respect du Design System\nFort de ces retours, j'ai modélisé l'ensemble des écrans sous **Figma** en me basant sur l'**Orange Design System**. J'ai créé un fond d'écran épuré affichant des symboles de langages informatiques en filigrane transparent pour refléter l'identité technique de l'agence tout en maintenant un contraste et une lisibilité parfaits.\n\n### Séparation en Deux Dépôts distincts (Clean Architecture)\nPour garantir une évolutivité et une testabilité maximales, nous avons découpé l'application en **deux dépôts Git strictly séparés** :\n- **Dépôt Data/Domain** : Cœur du système isolant la logique métier pure, les Use Cases, les entités du domaine (`User`, `Skill`, `Availability`) et les contrats d'interfaces d'accès aux données. Cette couche est totalement indépendante du framework visuel.\n- **Dépôt Front-End** : Contient l'interface utilisateur Flutter 3. Sa structure est découpée de manière modulaire par fonctionnalités, widgets réutilisables et vues adaptées pour le Web et le Mobile.\n\n### Gestion d'État BLoC, Routage AutoRoute & Navigation Responsive\nPour découpler la logique métier de la vue, j'ai mis en place le pattern **BLoC (Business Logic Component)** (`UserBloc`, `UserEvent`, `UserState`). La vue émet des événements réactifs écoutés par le BLoC qui exécute la logique métier et renvoie un nouvel état à l'UI.\n\nPour la navigation, j'ai configuré **AutoRoute** via un routeur centralisé. Enfin, j'ai conçu un widget sur-mesure adaptant automatiquement la mise en page selon qu'il s'agisse d'un écran Mobile, Tablette ou Web Desktop.",
      results:
        "J'ai contribué à aligner l'ensemble des acteurs métiers d'Orange Business autour d'une vision produit commune, concrétisée par une architecture logicielle propre et modulaire saluée par l'équipe.",
    },

    situation2: {
      label: "2. Supabase, PostgreSQL & RLS",
      title: "Situation 2 — Base de Données Supabase, Schéma PostgreSQL & Sécurité RLS",
      badge: "SGBD, API REST & Gouvernance des Données",
      framing:
        "En tant que développeur sur le projet, je devais participer au choix et à la mise en place d'une solution de base de données relationnelle performante et gratuite, tout en instaurant une sécurité d'accès rigoureuse sur les données des collaborateurs.",
      action:
        "Nous avons retenu **Supabase**, une alternative open-source reposant sur le SGBD relationnel **PostgreSQL**.\n\n### Modélisation de la Base de Données (MCD, MLD, MPD)\nJ'ai participé à la définition de la structure relationnelle :\n- **Table `USER`** : Stocke les informations personnelles, la profession, le TJM et la disponibilité.\n- **Table `SKILLS`** : Référentiel global des compétences techniques et fonctionnelles.\n- **Tables de descriptions et de niveaux** : Niveaux numériques de 1 à 5 et leurs descriptifs associés.\n- **Tables d'association et de rôles** : Matrice des privilèges (Administrateur, Manager, Commercial, Développeur).\n\n### APIs RESTful Auto-Générées & Supabase Storage\nSupabase génère automatiquement des APIs RESTful sécurisées à partir des tables PostgreSQL. Via le **SDK Flutter Supabase**, l'application effectue toutes ses opérations CRUD via des requêtes HTTP directes. J'ai également configuré **Supabase Storage** pour héberger en toute sécurité les CVs PDF des développeurs et leurs photos de profil.\n\n### Gouvernance & Sécurité au Niveau Ligne (Row Level Security - RLS)\nPour garantir le respect de la vie privée et la confidentialité des données RH chez Orange Business, j'ai écrit et déployé des politiques **Row Level Security (RLS)** directement dans PostgreSQL :\n- Un développeur ne peut modifier en écriture que sa propre fiche profil.\n- Les managers et administrateurs bénéficient de règles RLS privilégiées pour valider les compétences et réattribuer les rôles.\n- Les utilisateurs anonymes sont strictement bloqués par défaut.",
      results:
        "J'ai mis en place une infrastructure de données PostgreSQL robuste sous Supabase, garantissant une synchronisation temps réel, zéro coût d'hébergement et un respect strict des règles de sécurité d'entreprise via les politiques RLS.",
    },

    situation3: {
      label: "3. Management Agile & CI/CD",
      title: "Situation 3 — Implication Agile face aux Aléas d'Effectif, Entraide d'Équipe & CI/CD Azure",
      badge: "Gestion de Projet SCRUM, Pédagogie & DevOps",
      framing:
        "Le projet MyLab étant attribué aux développeurs en inter-contrat, l'équipe a subi d'importantes **fluctuations d'effectifs** : plusieurs développeurs ont été soudainement détachés sur des missions clients prioritaires en cours de sprint. Mon rôle a été de contribuer à maintenir la cohésion et le rythme de livraison malgré ces départs imprévus, tout en automatisant la chaîne CI/CD sous **Azure DevOps**.",
      action:
        "### Implication Agile & Gestion des Aléas d'Équipe (SCRUM)\nFace à la volatilité de l'effectif, j'ai pris des initiatives d'adaptation au sein du cadre agile :\n- **Réorganisations agiles & Diagramme de Gantt** : Lors des départs en mission, j'ai réévalué la charge de travail avec le chef de projet, réattribué les tickets sur Azure Boards et ajusté le diagramme de Gantt pour préserver les fonctionnalités critiques.\n- **Daily Standups & Entraide** : J'ai participé activement aux réunions quotidiennes de 9h30 pour suivre l'avancement, identifier les blocages et favoriser un climat d'entraide.\n- **Accompagnement & Pédagogie Technique** : Pour faciliter la prise en main de Flutter, du pattern BLoC et de la Clean Architecture par mes collègues juniors ou en reconversion, **j'ai animé plusieurs réunions de partage de connaissances** (**Tech Talks** sur BLoC et l'architecture logicielle). J'ai également instauré un canal Microsoft Teams dédié pour avertir l'équipe lors des merge de branches afin d'aider mes collègues sur les `git rebase` et éviter tout conflit de code.\n\n### Automation DevOps CI/CD sous Azure DevOps\nEn parallèle du travail d'équipe, j'ai rédigé les pipelines automatisés d'intégration continue sous Azure DevOps :\n- **Build Web** : Compilation automatisée de l'application Web avec un moteur de rendu optimisé pour des performances graphiques fluides.\n- **Environnement local & Diagnostics** : Validation des outils d'environnement local (émulateurs Android Studio et simulateur Xcode iOS).\n- **Builds Android & iOS** : Automatisation de la génération du binaire Android destiné au Play Store et du binaire iOS pour le déploiement sur **TestFlight**.",
      results:
        "Grâce à notre démarche d'entraide et de pédagogie entre pairs, l'équipe a surmonté la volatilité des effectifs dans un excellent esprit de solidarité. J'ai livré une infrastructure CI/CD d'entreprise automatisée sur Azure DevOps, capable d'effectuer des builds multi-plateformes en un clic.",
    },

    synthesis: {
      label: "Mon Bilan & Regard Critique",
      title: "Bilan global, Regard Critique & Lendemains du projet",
      badge: "Auto-Évaluation, Esprit d'Équipe & Posture Professionnelle",
      content:
        "### Compétences confirmées et apprentissages majeurs\nCe projet **MyLab** a été une expérience déterminante de ma formation et a concrétisé l'obtention de mon diplôme de **Concepteur Développeur d'Applications (CDA - Bac +3/4)**. Il m'a permis d'acquérir une solide maturité professionnelle :\n- **Écoute & Travail en Collectif** : Capacité à écouter et intégrer les attentes des différents acteurs au sein d'une équipe de développeurs pairs.\n- **Adaptabilité Agile** : Participation aux réajustements de sprints SCRUM et du diagramme de Gantt face aux départs imprévus des développeurs en mission client.\n- **Partage de Connaissances & Pédagogie** : Animation de réunions de partage de connaissances (**Tech Talks** sur Flutter BLoC et Clean Architecture) et soutien quotidien à mes collègues.\n- **Maîtrise Technique Multi-Plateformes & Cloud** : Développement sous Flutter 3 / Dart, BLoC pattern, Supabase PostgreSQL avec sécurité RLS et pipelines CI/CD Azure DevOps.\n\n### Valeur ajoutée pour Orange Business & Résultats clés\n- **Modernisation Applicative** : Remplacement du fichier Excel obsolète par une application réactive au service de l'agence.\n- **Cohésion d'Équipe & Esprit d'Entraide** : Consolidation de la communication transparente via Teams et les Daily meetings.\n- **Réussite Académique et Professionnelle** : Soutenance du mémoire félicitée par le jury lors de l'obtention de mon Titre Pro CDA.\n\n### Lendemains du Projet & Évolution vers Phaser.js\nL'application MyLab a été qualifiée et préparée pour l'hébergement web (Docaposte) et les stores mobiles d'entreprise (Play Store, App Store). Cette expérience m'a révélé une passion forte pour le développement d'applications réactives et le développement de jeux vidéo.\n\nInitialement, cette aventure m'avait donné l'envie de concevoir un projet de jeu vidéo personnel sous Flutter. Toutefois, dans une démarche d'optimisation et d'accessibilité en ligne directe sur navigateur web, j'ai effectué un pivot technique pour me tourner vers le framework dédié **Phaser.js**. Ce jeu vidéo web est actuellement en cours de développement actif !",
    },
  },
};

export const mylabEn = {
  title: "MyLab Skills — Cross-Platform App & Talent Management",
  shortDesc:
    "Cross-platform web and mobile skills, TJM & availability management app — Flutter 3, Dart, Supabase, BLoC, Azure DevOps.",
  definition:
    "**MyLab Skills** is a strategic enterprise cross-platform application (Web, Android, iOS) developed at Orange Business. It was built to replace an obsolete manual Excel file with a modern solution enabling real-time mapping of technical skills, soft skills, Daily Rates (TJM), and availability for agency developers.",
  framing:
    "I contributed to developing MyLab for my **CDA Bachelor's degree (Bac +3/4)** at Orange Business. The project leverages **Flutter 3 / Dart** for a single cross-platform codebase, paired with **Supabase (PostgreSQL BaaS)** and a dual-repository **Clean Architecture** (`Front-end` and `Data/Domain`). My scope included business requirements gathering, reactive component structuring, Supabase data governance, and collective agile collaboration among peer developers under **SCRUM**.",
  action:
    "As a participating developer working within a peer team, my work focused on 4 major pillars: functional requirements audit with stakeholder consensus and Flutter Front-End architecture (BLoC pattern, AutoRoute, ResponsiveWidget); data governance and row-level security under Supabase (PostgreSQL, SQL RLS, Storage); active contribution to agile organization amid team fluctuations with peer knowledge sharing; and authoring full Azure DevOps CI/CD pipelines for Web, Android, and iOS builds.",
  results:
    "I actively participated in building the **MyLab Skills** application which I successfully presented to the jury to earn my **CDA Bachelor's Degree (Bac +3/4)**. The solution eliminated Excel operational debt, provided instant visibility over Orange Business talents, and automated multi-platform CI/CD build chains under Azure DevOps.",
  critical:
    "This achievement served as a key milestone in my software engineering growth. It proved my ability to master modern technologies (Flutter, Dart, Supabase, Azure DevOps), demonstrate **active listening to business users**, foster peer support, and show self-organization within a project team.",

  tabs: {
    project: {
      label: "The Project",
      title: "Overview, Corporate Context & Business Challenges",
      badge: "Application Scope & Digital Transformation",
      content:
        "### Enterprise Context at Orange Business\nWithin Orange Business Services (OBS), a subsidiary of the Orange group uniting over 30,000 B2B employees and 9,700 digital experts worldwide, I joined an internal Digital Services Agency. Our agency comprises 50 developers, 6 project managers (across Web, Mobile, and Data tracks), 6 sales reps, managers, and a local HR team.\n\n### Business Problem: The Manual Excel Sheet\nBefore **MyLab Skills** was built, tracking skills and availability for our agency developers relied on a shared manual Excel file. This tool suffered from critical operational flaws:\n- **Stale Data**: The file was rarely updated, leading to information lag during mission staffing.\n- **Inter-Departmental Friction**: Sales reps complained about delays in finding suitable profiles at the right Daily Rate (TJM), while developers felt undervalued regarding their true technical and soft skills.\n- **Lack of Mobile Ergonomics**: Impossible for a sales rep or manager on the move to quickly access profile cards from a smartphone.\n\n### MyLab Application Objectives\n- **Developer Autonomy**: Enable each developer to easily update skills (technologies, levels 1 to 5, soft skills) and declare availability.\n- **Centralization & Decision Visibility**: Provide sales reps and project managers with a fluid platform to view profile cards, filter by business criteria, and download PDF CVs in one click.\n- **Single Cross-Platform Experience**: Deliver an accessible app on desktop Web and Android/iOS smartphones from a single Flutter 3 codebase.\n\n### Global Tech Stack\n- **Front-End & Mobile**: Flutter 3, Dart, BLoC Pattern, AutoRoute, responsive layout widgets.\n- **Back-End & Database**: Supabase BaaS (PostgreSQL, auto-generated RESTful APIs, Supabase Auth, Supabase Storage).\n- **Architecture**: Dual Git repository split (`Front-end` and `Data/Domain`) adhering strictly to **Clean / Hexagonal Architecture**.\n- **DevOps & CI/CD**: Azure DevOps Pipelines (automated builds for Web, Android packages, and iOS TestFlight).\n\n### My Role & Involvement in the Agile Team\nI worked on this project as a **participating developer** during my work-study program for my **CDA Bachelor's degree (Bac +3/4)** at Orange Business. Working collectively within the inter-contract developer team alongside our project manager, I actively participated across the development cycle following **SCRUM** methodology (2-week sprints, 9:30 AM Daily syncs, Azure Boards ticket tracking).",
    },

    situation1: {
      label: "1. Audit, Figma & Clean Arch BLoC",
      title: "Situation 1 — Requirements Audit, Interpersonal Mediation & Clean BLoC Architecture",
      badge: "Requirements Engineering & Interpersonal Communication",
      framing:
        "Before designing technical architecture, my first task was conducting **active listening** across stakeholder groups to gather precise requirements at Orange Business.",
      action:
        "I participated in discussions and summarized expectations across roles:\n- **Sales Reps**: Demanded featuring top 3 soft skills (validated by reference manager for objectivity), displaying ideal and minimum TJM (Daily Rate), and providing updated LinkedIn profile links.\n- **Talent Acquisition Specialists**: Requested detailed project history for developers (tech stack, duration, team size, client-site vs plateau assignment).\n- **Project Managers & Managers**: Required a clear skill validation workflow and an bench resource allocation filter.\n- **Developers**: Demanded an ultra-fast, rewarding interface requiring only a few clicks to update their profiles.\n\n### Figma Graphic Design & Design System Compliance\nBased on feedback, I designed all wireframes in **Figma** adhering strictly to the **Orange Design System**. I created a sleek background theme displaying transparent programming language symbols in watermarks to reflect agency identity while preserving readability.\n\n### Dual Repository Separation (Clean Architecture)\nTo guarantee maximum scalability and testability, we separated the project into **two distinct Git repositories** following **Clean Architecture**:\n- **Data/Domain Repository**: Serves as the core system isolating pure business logic, Use Cases, domain entities (`User`, `Skill`, `Availability`), and data access contract interfaces. This layer is entirely independent of the visual framework.\n- **Front-End Repository**: Houses the Flutter 3 user interface structured modularly by feature, reusable widgets, and tailored Web/Mobile view folders.\n\n### BLoC State Management, AutoRoute & Responsive Layouts\nTo decouple business logic from views, I implemented **BLoC architecture (Business Logic Component)** (`UserBloc`, `UserEvent`, `UserState`). Views dispatch reactive events consumed by the BLoC which executes business logic and emits a new state to the UI.\n\nFor navigation, I integrated **AutoRoute** via a centralized router. Finally, I engineered a custom responsive widget dynamically switching between Mobile, Tablet, and Web Desktop layouts based on screen width.",
      results:
        "I contributed to aligning all business stakeholders at Orange Business around a shared product vision, realized through a clean, modular software architecture praised by the team.",
    },

    situation2: {
      label: "2. Supabase, PostgreSQL & RLS",
      title: "Situation 2 — Supabase Database, PostgreSQL Schema & Row Level Security (RLS)",
      badge: "SGBD, REST APIs & Data Governance",
      framing:
        "As a project developer, I needed to participate in selecting and setting up a performant, cost-effective relational database solution while establishing rigorous access security over employee data.",
      action:
        "We selected **Supabase**, an open-source alternative powered by the **PostgreSQL** relational SGBD.\n\n### Database Modeling (MCD, MLD, MPD)\nI participated in defining the relational structure:\n- **`USER` Table**: Personal details, profession, TJM, and availability.\n- **`SKILLS` Table**: Global skill and framework repository.\n- **Level Description Tables**: Numeric levels 1 to 5 and descriptions.\n- **Role & Permission Tables**: Access control matrix (Admin, Manager, Sales, Developer).\n\n### Auto-Generated RESTful APIs & Supabase Storage\nSupabase automatically generates secure RESTful APIs from PostgreSQL tables. Via the **Supabase Flutter SDK**, the app performs all CRUD operations through direct HTTP requests. I also configured **Supabase Storage** to securely host developer PDF CVs and profile pictures.\n\n### Governance & Security via Row Level Security (RLS)\nTo guarantee privacy and corporate HR data confidentiality at Orange Business, I authored and deployed **Row Level Security (RLS)** policies directly in PostgreSQL:\n- Developers can only write to their own profile row.\n- Managers and admins hold extended RLS privileges to validate skills and reassign roles.\n- Anonymous users are strictly blocked by default.",
      results:
        "I deployed a robust, secure PostgreSQL data infrastructure under Supabase delivering real-time synchronization, zero hosting costs, and total data security via SQL RLS policies.",
    },

    situation3: {
      label: "3. Agile Leadership & CI/CD",
      title: "Situation 3 — Agile Involvement Amid Staffing Fluctuations, Peer Support & Azure CI/CD",
      badge: "SCRUM Project Management, Mentorship & DevOps",
      framing:
        "Since MyLab was assigned to inter-contract developers, the team experienced severe **staffing volatility**: several developers were suddenly assigned to urgent external client missions mid-sprint. My role was contributing to maintaining team cohesion and delivery velocity despite unplanned departures, while automating the CI/CD pipeline under **Azure DevOps**.",
      action:
        "### Agile Involvement & Team Volatility Management (SCRUM)\nFacing team volatility, I took initiative within our agile process:\n- **Agile Re-Organization & Gantt Adjustments**: When developers departed for client missions, I re-evaluated workload with the project manager, redistributed tickets on Azure Boards, and adjusted the Gantt chart to preserve critical features.\n- **Daily Standups & Support**: I actively participated in 9:30 AM Daily meetings to track progress, identify blockers, and foster peer support.\n- **Technical Guidance & Knowledge Sharing**: To help junior colleagues master Flutter, BLoC pattern, and Clean Architecture, **I led technical knowledge-sharing workshops** (**Tech Talks** on BLoC and software architecture). I also established a dedicated Microsoft Teams channel to notify the team upon branch merges, helping colleagues with `git rebase` procedures to prevent code conflicts.\n\n### CI/CD DevOps Automation under Azure DevOps\nIn parallel with team collaboration, I authored continuous integration pipelines under Azure DevOps:\n- **Web Build**: Automated web application compilation with an optimized rendering engine for smooth graphical performance.\n- **Local Testing & Diagnostics**: Validated local dev environment tools (Android Studio emulators and Xcode iOS simulator).\n- **Android & iOS Builds**: Automated generation of Android binaries for Google Play Store and iOS binaries for **TestFlight** distribution.",
      results:
        "Through peer support and mentorship, the team overcame staffing volatility with strong solidarity. I deployed an automated enterprise CI/CD infrastructure on Azure DevOps delivering 1-click multi-platform builds.",
    },

    synthesis: {
      label: "My Summary & Critical View",
      title: "Overall Retrospective, Critical View & Project Aftermath",
      badge: "Self-Evaluation, Teamwork & Professional Posture",
      content:
        "### Confirmed Skills & Key Learnings\nThis **MyLab Skills** project was a key milestone in my training and culminated in earning my **Application Developer Bachelor's Degree (CDA - Bac +3/4)**. It allowed me to acquire solid professional maturity:\n- **Listening & Teamwork**: Capability to actively listen to and integrate stakeholder expectations (sales, managers, HR, developers) within a project team.\n- **Agile Adaptability**: Active participation in SCRUM sprint and Gantt chart adjustments during unplanned developer departures to client missions.\n- **Knowledge Sharing & Mentorship**: Leading technical knowledge-sharing workshops (**Tech Talks** on Flutter BLoC and Clean Architecture) and daily peer support.\n- **Multi-Platform Technical & Cloud Mastery**: Flutter 3 / Dart development, BLoC pattern, Supabase PostgreSQL with RLS security, and Azure DevOps CI/CD pipelines.\n\n### Added Value for Orange Business & Key Results\n- **Application Modernization**: Replaced obsolete manual Excel sheets with a responsive application serving the agency.\n- **Team Cohesion & Peer Support Culture**: Consolidated transparent communication via Teams and Daily meetings.\n- **Academic & Professional Success**: Thesis defense praised by the jury during my CDA Bachelor's Degree graduation.\n\n### Project Aftermath & Evolution to Phaser.js\nThe MyLab application was qualified and prepared for web hosting (Docaposte) and mobile enterprise stores (Play Store, App Store). This experience revealed a strong passion for reactive application and web game development.\n\nInitially, this journey inspired me to design a personal video game project in Flutter. However, to optimize for web browser simplicity and instant online accessibility, I executed a technical pivot to the dedicated **Phaser.js** web game framework. This web game is currently under active development!",
    },
  },
};
