export const portailRhFr = {
  title: "Portail RH & Redirection d'Outils",
  shortDesc:
    "Application web d'entreprise centralisant les outils RH d'Orange — Angular 18, NestJS, MariaDB, Docker & Analytics Power BI.",
  definition:
    "Le **Portail RH** est une application web d'entreprise stratégique chez Orange Business. Il centralise l'accès à l'ensemble des outils, applications et ressources RH pour les collaborateurs, avec un système de redirection dynamique et un back-office d'administration.\n\nMon intervention sur ce projet s'est structurée autour de **5 phases chronologiques majeures** au cours de ma 2ème année d'alternance (Titre Pro CDA Bac+3) :\n1. **Reprise & assainissement** du projet suite à la démission du développeur initial.\n2. **Onboarding & formation d'un collaborateur** pour faire face à un fort pic de demandes client.\n3. **Gestion de crise & rattrapage Front-End** au retour de vacances suite aux dérives de code du collaborateur isolé.\n4. **Consolidation TMA & enrichissement du Back-Office** (module News, bordereau d'alerte, traçabilité RGPD et export CSV).\n5. **Conception & déploiement autonome d'un module d'Analytics maison** dédié à l'alimentation de tableaux de bord Power BI.",
  framing:
    "Chaque étape chronologique du projet a posé des contraintes d'architecture spécifiques qui ont dicté mes choix techniques :\n\n- **Phase 1 — Assainissement BDD & Pattern DTO** : L'application initiale souffrait d'une absence de relations d'intégrité référentielle en BDD (MariaDB) et d'une manipulation directe des entités par les services NestJS. J'ai reconstruit les clés étrangères sous TypeORM, instauré un découpage strict par **DTO (Data Transfer Objects)** avec mappers dédiés, et supprimé les scripts JS pur qui contournaient NestJS et Angular.\n- **Phase 1 — Environnement Dockerisé sur-mesure** : Afin de simplifier l'installation locale, j'ai conçu une architecture **Docker multi-stage** (NestJS + MariaDB + PHPMyAdmin) orchestrée par `docker compose up -d --build`, offrant un environnement de développement 1-click.\n- **Phase 2 — Cadrage de l'onboarding** : Face à l'augmentation des demandes du client, le Chef de Projet a affecté un collaborateur (spécialiste mobile/Flutter) sur le projet. J'ai cadré un plan de montée en compétences ciblé sur Angular 18, les flux HTTP et les principes d'architecture Web.\n- **Phase 5 — Cadrage du module Analytics** : Pour mesurer les usages collaborateurs, j'ai étudié plusieurs options (dont Grafana) avant de faire valider une **architecture Analytics maison**. Ce choix permettait de capturer les événements d'usage au plus près de la BDD et de formater nativement les données pour les restitutions Power BI.",
  action:
    "Voici le déroulement détaillé de mes actions à travers les 5 phases du projet :\n\n- **Étape 1 : Reprise du projet & TMA (Début d'alternance)**\nAprès le départ du développeur précédent, j'ai travaillé en binôme avec mon Lead Dev pour prendre en main le code. J'ai assuré la Tierce Maintenance Applicative (TMA) tout en réarchitecturant le Back-End NestJS (mise en place des DTOs et des relations MariaDB).\n\n- **Étape 2 : Accélération des demandes & Mentorat d'un collaborateur**\nLe client ayant demandé un volume important de nouvelles fonctionnalités avec une refonte graphique, le Chef de Projet m'a confié l'onboarding d'un collaborateur en intercontrat. J'ai animé des sessions quotidiennes de formation sur Angular 18 et les requêtes HTTP. Identifiant des lacunes fondamentales sur l'architecture Web chez ce collaborateur, j'ai émis une alerte préventive auprès du Chef de Projet avant de partir pour 3 semaines de vacances afin de prévoir un accompagnement.\n\n- **Étape 3 : Absence du Lead Dev, crise & rattrapage Front-End post-vacances**\nPendant mes vacances, le Lead Dev a été absent de manière imprévue, laissant le collaborateur seul. À mon retour, j'ai constaté un code Front-End très dégradé par des copier-coller bruts d'IA générative sans contrôle d'architecture. J'ai gardé mon sang-froid, réorganisé le planning des tickets restants et consacré plusieurs jours à réécrire et restructurer la partie Front (composants Angular isolés, typage strict, gestion d'erreurs).\n\n- **Étape 4 : Pérennisation & Évolutions Back-Office**\nLe calme revenu, j'ai poursuivi la TMA en autonomie (avec revues de code du Lead Dev). J'ai réalisé la refonte graphique de plusieurs pages, corrigé les redirections et les styles CSS, puis développé les modules d'administration : gestion des articles RH (News), **bordereau d'alerte d'urgence en temps réel**, export CSV des utilisateurs et traçabilité du consentement RGPD.\n\n- **Étape 5 : Développement autonome du module Analytics (Période récente)**\nJ'ai conçu et développé à 100% la brique d'Analytics maison. Elle capture les parcours utilisateurs, les pages les plus consultées, l'utilisation de la recherche et des favoris, ainsi que les tops applications RH. Développé seul puis validé par le Lead Dev, le module a été poussé en Préproduction sans aucune régression et attend le Go Prod final.",
  results:
    "Les résultats obtenus reflètent la résolution progressive de chaque phase du projet :\n\n- **Après la Phase 1 (Assainissement)** : Suppression complète des fuites de données et des anomalies d'intégrité grâce à la refonte MariaDB/NestJS en DTOs.\n- **Après les Phases 2 & 3 (Crise & Rattrapage)** : L'application a été livrée dans les temps réajustés avec une entière satisfaction du client. Un REX d'équipe a permis d'adapter les modalités d'encadrement des collaborateurs et l'usage des IA de code.\n- **Après la Phase 4 (Back-Office)** : Les administrateurs RH disposent d'outils autonomes pour diffuser des alertes urgentes et exporter les preuves de conformité RGPD.\n- **Après la Phase 5 (Analytics)** : Le système de suivi de trafic est 100% opérationnel en Préproduction, prêt à alimenter les tableaux de bord Power BI de la direction.",
  critical:
    "Chaque étape de ce projet m'a apporté des enseignements ciblés sur ma pratique professionnelle :\n\n- **Lien avec la Phase 3 (Gestion de crise)** : Cette épreuve a prouvé mon sang-froid et ma capacité à réorganiser un sprint sous pression. Elle m'a également sensibilisé aux risques des IA génératives : sans relecture critique et sans maîtrise de l'architecture, l'IA génère de la dette technique instantanée.\n- **Lien avec la Phase 2 (Mentorat)** : J'ai appris l'importance d'un suivi continu lors du changement de stack d'un collaborateur (du mobile vers le web) et la nécessité d'adapter la charge aux compétences réelles.\n- **Lien avec les Phases 4 & 5 (Autonomie)** : Ma progression sur ce projet illustre mon passage d'une reprise de code guidée à la conception autonome d'architectures critiques (module Analytics pour Power BI) validées dès le premier déploiement.",
};

export const portailRhEn = {
  title: "HR Portal & Tool Redirection",
  shortDesc:
    "Enterprise web app centralizing Orange HR tools — Angular 18, NestJS, MariaDB, Docker & Power BI Analytics.",
  definition:
    "The **HR Portal** is a strategic enterprise web application at Orange Business. It centralizes access to all HR tools, applications, and resources for employees through a dynamic redirection system and an administrative back-office.\n\nMy involvement in this project unfolded across **5 major chronological phases** during my 2nd year of work-study (Bachelor's degree in Application Design):\n1. **Project takeover & sanitization** following the initial developer's resignation.\n2. **Onboarding & training of a team member** to handle a peak in client feature requests.\n3. **Crisis management & Front-End refactoring** upon return from vacation following degraded code from the isolated team member.\n4. **Maintenance consolidation & Back-Office enrichment** (News module, emergency alert banner, GDPR consent tracking, and CSV export).\n5. **Autonomous design & deployment of an in-house Analytics module** dedicated to feeding Power BI dashboards.",
  framing:
    "Each chronological step presented specific architectural constraints that governed my technical decisions:\n\n- **Phase 1 — BDD Sanitization & DTO Pattern**: The legacy app suffered from a lack of relational database integrity in MariaDB and direct entity manipulation by NestJS services. I rebuilt foreign keys using TypeORM, introduced strict **DTO (Data Transfer Objects)** separation with dedicated mappers, and removed raw JS scripts bypassing NestJS and Angular.\n- **Phase 1 — Custom Dockerized Environment**: To simplify local setup, I designed a **multi-stage Docker** architecture (NestJS + MariaDB + PHPMyAdmin) orchestrated by `docker compose up -d --build`, offering a 1-click dev environment.\n- **Phase 2 — Onboarding Framing**: Facing an influx of client requests, the Project Manager assigned a team member (Flutter mobile specialist) to the project. I structured a training plan focused on Angular 18, HTTP streams, and Web architecture.\n- **Phase 5 — Analytics Module Framing**: To measure user engagement, I evaluated several options (including Grafana) before securing approval for an **in-house Analytics architecture**. This choice enabled event capture directly at the BDD layer and native data formatting for Power BI reports.",
  action:
    "Here is the detailed progression of my actions across the 5 project phases:\n\n- **Step 1: Project Takeover & Maintenance (Start of work-study)**\nFollowing the departure of the previous developer, I paired with my Lead Dev to take ownership of the codebase. I managed application maintenance while refactoring the NestJS Back-End (implementing DTOs and MariaDB relations).\n\n- **Step 2: Accelerated Requests & Team Member Mentorship**\nWith the client requesting a large volume of new features alongside a UI redesign, the Project Manager entrusted me with onboarding a team member on inter-contract. I conducted daily training sessions on Angular 18 and HTTP requests. Identifying fundamental web architecture gaps, I issued a preventive alert to the Project Manager before leaving for a 3-week vacation to ensure support was arranged.\n\n- **Step 3: Lead Dev Absence, Crisis & Post-Vacation Front-End Rework**\nDuring my vacation, the Lead Dev was unexpectedly absent, leaving the team member unassisted. Upon return, I discovered severely degraded Front-End code resulting from unverified generative AI copy-pasting. Staying composed, I restructured the remaining sprint backlog and dedicated several days to rewriting and restructuring the Front-End (isolated Angular components, strict typing, error handling).\n\n- **Step 4: Consolidation & Back-Office Features**\nOnce stability was restored, I continued maintenance independently (with Lead Dev code reviews). I completed UI redesigns across several pages, fixed CSS/redirection bugs, and developed admin modules: HR News management, a **real-time emergency alert banner**, CSV user export, and GDPR consent auditability.\n\n- **Step 5: Autonomous Analytics Module Development (Recent Period)**\nI independently designed and built the in-house Analytics engine from scratch. It tracks user journeys, top-visited pages, search and favorite feature usage, and top HR tools. Developed solo and reviewed by the Lead Dev, the module was pushed to Preproduction with zero regressions and awaits final Production Go-Live.",
  results:
    "The results achieved demonstrate the progressive resolution of each project phase:\n\n- **Post-Phase 1 (Sanitization)**: Complete elimination of data leaks and integrity issues thanks to the MariaDB/NestJS DTO refactoring.\n- **Post-Phases 2 & 3 (Crisis & Recovery)**: Delivered the app within adjusted timelines with full client satisfaction. Team retrospective formalized onboarding protocols and AI code assistance governance.\n- **Post-Phase 4 (Back-Office)**: HR admins gained autonomous tools to broadcast emergency alerts and export audit-ready GDPR compliance proofs.\n- **Post-Phase 5 (Analytics)**: The audience tracking system is 100% operational in Preproduction, ready to supply usage data to executive Power BI dashboards.",
  critical:
    "Each phase of this project yielded targeted insights for my professional development:\n\n- **Link to Phase 3 (Crisis Management)**: Proved my composure and ability to reorganize a sprint under pressure. Highlighted the risks of generative AI: without human review and architectural mastery, AI generates immediate technical debt.\n- **Link to Phase 2 (Mentorship)**: Taught me the importance of continuous guidance when a team member shifts technology stacks (from mobile to web) and matching workloads to actual skill levels.\n- **Link to Phases 4 & 5 (Autonomie)**: My progression on this project illustrates my evolution from guided code maintenance to the autonomous design of critical architecture (Power BI Analytics engine) validated on initial deployment.",
};
