export const autonomeFr = {
  title: "Autonome",
  shortDesc: "Capacité à travailler de manière indépendante et proactive",
  definition:
    "Pour moi, **l'autonomie professionnelle** se définit comme ma capacité à accomplir mes missions de manière **indépendante, proactive et responsable**, tout en respectant le cadre méthodologique et les objectifs fixés par mon organisation. Elle implique non seulement ma maîtrise technique des outils et des processus, mais également mon aptitude à prendre des **décisions éclairées** face à des situations imprévues ou complexes.\n\nJe considère qu'être autonome ne signifie pas travailler de manière isolée, mais savoir évoluer en **autogestion** tout en identifiant le moment opportun pour solliciter l'aide de ma hiérarchie ou de mes pairs.\n\nDans mon ancien secteur médico-social, cette compétence m'était indispensable car elle garantissait la sécurité des personnes vulnérables dans des environnements privatifs dépourvus de supervision directe. Dans mon activité actuelle d'ingénieur logiciel, elle se traduit par ma prise en charge complète du cycle de vie d’une fonctionnalité, de l’analyse du besoin à son déploiement en production.\n\nCette autonomie me permet d'alléger la charge de supervision de mes chefs de projet et de mes référents techniques, tout en fluidifiant le rythme de nos cycles de développement. Elle requiert de ma part une grande **rigueur organisationnelle**, une forte capacité d'auto-évaluation et un sens aigu de ma responsabilité professionnelle.",
  proofs:
    "J'ai d'abord illustré cette compétence durant mon parcours de neuf années dans l'accompagnement médico-social, où j'effectuais mes interventions au domicile des usagers en **totale autogestion**. À ce titre, mon accompagnement d'une personne atteinte de la maladie de Charcot sous ventilation artificielle par trachéotomie constituait une mise en pratique particulièrement exigeante.\n\nAyant bénéficié d'une formation spécifique aux aspirations endotrachéales, je **réalisais de manière autonome** sa toilette complète au lit, sa mobilisation physique sécurisée et l'application stricte des protocoles d'aspiration bronchique en cas d'encombrement respiratoire vital. Mon autonomie s'étendait également à la configuration et à l'installation de ses outils d’aide à la communication, notamment un système de poursuite oculaire (caméra Tobii) que je réglais méticuleusement pour lui permettre d’accéder de façon autonome à son ordinateur.\n\nPlus récemment, dans mon rôle de développeur d'applications, j'ai mis cette autonomie en pratique lors du déploiement en production de fonctionnalités d'analyse d'audience sur le portail de redirection RH. Le client ayant validé tardivement les essais en pré-production, la demande de mise en production m'a été formulée à mon arrivée le matin même, pour une exécution immédiate.\n\nEn raison de l'absence imprévue de mon référent technique, mon chef de projet m'a demandé si j'étais capable de mener cette intervention seul. Connaissant le projet depuis deux ans et ayant participé à quatre ou cinq déploiements encadrés, j'ai accepté de **prendre cette responsabilité**.\n\nJ'ai rigoureusement suivi la procédure établie : exécution locale des tests d'intégration, vérification des variables d'environnement sur le tableau de bord cloud, lancement de la compilation du build de production et déclenchement de la migration de la base de données relationnelle. Le portail a été mis à jour avec succès, sans aucune régression ni interruption de service pour les utilisateurs finaux.",
  selfCritique:
    "Dans le cadre médico-social, l’intervention autonome auprès d’un patient trachéotomisé représentait la seule réponse opérationnelle viable pour garantir son maintien à domicile en toute sécurité, exigeant le strict respect des gestes techniques appris.\n\nPour la mise en production logicielle, accepter cette tâche sans mon référent technique était une **décision calculée et sécurisée**. Avant d'initier la moindre action sur l'infrastructure CloudFoundry, j'ai anticipé tous les scénarios de panne potentiels (perte de connexion à la base de données, erreur de conteneurisation ou crash du serveur cloud).\n\nPour cela, j'ai effectué un dump complet et préventif de la base de données MySQL et j'ai conservé le numéro de tag Git exact de la version stable précédente de l'application. Cette stratégie m'aurait permis d'opérer un rollback complet et immédiat de l'API et du Front-end en moins de deux minutes en cas d'anomalie détectée lors de la phase de post-déploiement.",
  hindsight:
    "Avec le recul, mon expérience d'auxiliaire de vie m'a inculqué une **tolérance élevée au stress** et le sens des priorités en situation d'urgence vitale, des qualités comportementales précieuses en ingénierie logicielle.\n\nRéaliser ce déploiement critique en autonomie a renforcé ma légitimité technique au sein de l'équipe et a démontré ma capacité à rester calme sous la pression. Pour un recruteur, cela prouve que je suis capable de m'approprier rapidement des processus de livraison complexes et de prendre des **décisions techniques responsables** avec méthode, sans nécessiter de supervision constante.",
  evolution:
    "Pour faire évoluer cette compétence, mon objectif est d'abord de maintenir ce niveau d'exigence et de rigueur opérationnelle sur l'ensemble de mes futurs projets.\n\nPar ailleurs, je consolide mon **autonomie technique** sur le long terme par une veille technologique quotidienne et active. Je reste particulièrement attentif aux évolutions de l'écosystème, notamment le développement des modèles d'intelligence artificielle ou les nouvelles pratiques de conception logicielle.",
};

export const autonomeEn = {
  title: "Autonomous",
  shortDesc: "Ability to work independently and proactively",
  definition:
    "For me, **professional autonomy** is defined as my ability to carry out my missions **independently, proactively, and responsibly**, while respecting the methodological framework and objectives set by my organization. It involves not only technical mastery of tools and processes, but also my aptitude to make **informed decisions** in unexpected or complex situations.\n\nI consider that being autonomous does not mean working in isolation, but knowing how to evolve in **self-management** while identifying the right time to seek help from hierarchy or peers.\n\nIn my former healthcare and social sector, this skill was indispensable as it guaranteed the safety of vulnerable individuals in private environments lacking direct supervision. In my current activity as a software engineer, it translates to taking full ownership of a feature's lifecycle, from requirements analysis to production deployment.",
  proofs:
    "I first illustrated this skill during my nine-year career in healthcare support, performing home visits in **total self-management**. My support for an individual suffering from ALS under artificial ventilation via tracheostomy constituted a particularly demanding application.\n\nHaving received specific training in endotracheal suctioning, I **autonomously performed** full bed baths, safe physical transfers, and strict application of bronchial suctioning protocols in cases of vital respiratory distress. My autonomy also extended to configuring and installing communication aid tools, notably an eye-tracking system (Tobii camera) that I meticulously adjusted to enable independent computer access.\n\nMore recently, as an application developer, I put this autonomy into practice during the production deployment of audience analytics features on the HR redirection portal. With late client validation in pre-production, the production release request came upon my arrival in the morning for immediate execution.\n\nDue to the unexpected absence of my tech lead, my project manager asked if I could execute the intervention alone. Knowing the project for two years and having participated in four or five guided deployments, I accepted **taking on this responsibility**.\n\nI rigorously followed established procedures: local integration tests, verifying environment variables on the cloud dashboard, building production artifacts, and triggering relational database migration. The portal was successfully updated without regressions or downtime.",
  selfCritique:
    "In healthcare, autonomous intervention for a tracheostomized patient was the only viable operational response to guarantee safe home care. For software deployment, accepting the task without my tech lead was a **calculated and safe decision**. Before taking action on CloudFoundry infrastructure, I anticipated all failure scenarios.\n\nTo prepare, I took a full preventive MySQL dump and preserved the exact Git tag of the previous stable version. This strategy enabled a complete rollback in under two minutes if anomalies arose post-deployment.",
  hindsight:
    "In hindsight, my experience as a caregiver instilled **high stress tolerance** and vital emergency prioritization—precious behavioral qualities in software engineering.\n\nExecuting this critical deployment autonomously reinforced my technical credibility within the team and proved my calm under pressure. For a recruiter, it demonstrates my capability to rapidly adopt complex delivery workflows and make **responsible technical decisions** methodically.",
  evolution:
    "To advance this skill, my primary goal is to maintain this level of rigor across future projects.\n\nFurthermore, I consolidate long-term **technical autonomy** through active daily tech watching, keeping a close eye on AI models and modern software design practices.",
};
