export const dartFr = {
  title: "Dart",
  shortDesc: "Langage orienté objet fortement typé optimisé pour le multiplateforme",
  definition:
    "Pour moi, **Dart** est bien plus que le langage support de Flutter : c'est un langage de programmation moderne, fortement typé et orienté objet, spécialement conçu par Google pour le développement d'applications multiplateformes performantes.\n\nDart combine deux modes de compilation complémentaires : le mode **JIT (Just-In-Time)** pendant la phase de développement, autorisant le *Stateful Hot Reload* pour une boucle de retour instantanée, et la compilation **AOT (Ahead-Of-Time)** vers du code machine natif (ARM / x86) pour la production. Grâce à son système de typage strict, sa sécurité anti-nulle garantie (**Sound Null Safety**) et ses fonctionnalités avancées (extensions, mixins, programmation asynchrone par `Future` et `Stream`), Dart offre un cadre d'ingénierie extrêmement robuste.",
  proofs:
    "J'ai utilisé et approfondi le langage Dart chez Orange Business lors du projet d'apothéose CDA **MyLab / Compétences** (Web, Android et iOS) ainsi que sur la maintenance de l'application *My Resume* :\n\n- **Isolation du Domaine en Dart Pur (Clean Architecture)** : L'une des décisions d'architecture majeures du projet MyLab a été d'isoler l'intégralité de la couche **Domain** (entités métier, modèles de données et cas d'utilisation / Use Cases) en **100 % Dart pur**, totalement affranchi de tout composant ou paquet lié à Flutter. Ce choix stratégique a permis de tester la logique métier de l'application de façon purement unitaire à l'aide du framework `test` de Dart et de la bibliothèque `Mockito`, sans avoir besoin d'instancier d'écrans visuels ou d'émulateurs.\n\n- **Fiabilité grâce au Sound Null Safety** : J'ai exploité le système **Sound Null Safety** de Dart (`Type?`, `required`, `final`, `late`) pour éliminer l'ensemble des erreurs de pointeur nul dès la phase de compilation. Cela s'est traduit par la conception de modèles de données immuables et de DTOs fortement typés (`fromMap`, `toMap`, `jsonDecode`) pour parser de manière totalement sécurisée les réponses JSON en provenance de l'API Supabase / PostgreSQL.\n\n- **Programmation Asynchrone et Flux de Données (`Stream`)** : Pour alimenter les blocs de gestion d'état BLoC de l'application, j'ai utilisé les mécanismes natifs de Dart basés sur les `Future` et les `Stream` (`async*` / `yield`). Cela a permis de traiter les flux de données asynchrones (authentification, mises à jour des compétences en temps réel, filtres de disponibilité) de manière totalement réactive et sans effet de bord.\n\n- **Méthodes d'extension et utilitaires réutilisables** : J'ai conçu des méthodes d'extension Dart (`extension StringUtils on String`) pour encapsuler les expressions régulières de validation de formulaires (emails, mots de passe) et les formatages de dates, rendant le code de l'application modulaire, lisible et facilement maintenable par l'ensemble de l'équipe.",
  selfCritique:
    "Venant de l'écosystème JavaScript, l'adoption de Dart a exigé une rigueur accrue sur le typage statique et la gestion de la nularité. Au début du projet, la tentation était parfois grande d'utiliser l'opérateur d'assertion non-nulle (`!`) ou le mot-clé `late` pour contourner certaines contraintes du compilateur. J'ai rapidement corrigé cette habitude en modélisant explicitement le statut optionnel de chaque variable dès la conception des entités.",
  hindsight:
    "Avec le recul, la clarté syntaxique de Dart et sa compilation AOT native en font l'un des langages client les plus fiables du marché. Avoir rédigé la couche Domaine de MyLab en Dart pur reste pour moi la meilleure preuve qu'un code bien structuré transcende les frameworks graphiques et garantit une stabilité applicative maximale.",
  evolution:
    "Je continue de suivre de près l'évolution du langage Dart (notamment les versions Dart 3+ apportant le *Pattern Matching*, les *Records*, les destructurations d'objets et les modificateurs de classes `sealed` et `final`). Je mobilise quotidiennement cette rigueur de typage et de conception orientée objet sur l'ensemble de mes projets d'ingénierie logicielle.",
};

export const dartEn = {
  title: "Dart",
  shortDesc: "Strongly typed object-oriented language optimized for cross-platform apps",
  definition:
    "For me, **Dart** is far more than Flutter's supporting language: it is a modern, strongly typed, object-oriented programming language specifically engineered by Google for building performant cross-platform applications.\n\nDart combines two complementary compilation modes: **JIT (Just-In-Time)** compilation during development, enabling *Stateful Hot Reload* for an instant feedback loop, and **AOT (Ahead-Of-Time)** compilation into native machine code (ARM / x86) for production. Featuring strict static typing, **Sound Null Safety**, and advanced language constructs (extensions, mixins, `Future`/`Stream` asynchronous programming), Dart provides an extremely robust engineering foundation.",
  proofs:
    "I utilized and deepened my expertise in Dart at Orange Business during the CDA graduation project **MyLab / Skills** (Web, Android, and iOS) as well as maintenance on the *My Resume* application:\n\n- **Pure Dart Domain Layer Isolation (Clean Architecture)**: One of the primary architecture decisions on MyLab was isolating the entire **Domain** layer (business entities, data models, and Use Cases) in **100% pure Dart**, completely free of any Flutter UI dependencies. This strategic choice enabled testing core application logic in a purely unit-tested environment using Dart's native `test` framework and `Mockito`, without requiring visual screens or device emulators.\n\n- **Reliability via Sound Null Safety**: I leveraged Dart's **Sound Null Safety** (`Type?`, `required`, `final`, `late`) to eliminate null pointer exceptions at compile time. This translated into designing immutable data models and strongly typed DTOs (`fromMap`, `toMap`, `jsonDecode`) to safely parse raw JSON payloads originating from the Supabase / PostgreSQL API.\n\n- **Asynchronous Data Streams (`Stream`)**: To feed the application's BLoC state management components, I utilized native Dart asynchronous mechanisms based on `Future` and `Stream` (`async*` / `yield`). This enabled handling real-time data flows (authentication, live skill updates, availability filters) in a fully reactive manner without side effects.\n\n- **Extension Methods and Reusable Utilities**: I created custom Dart extension methods (`extension StringUtils on String`) to encapsulate regex form validations (emails, passwords) and date formatting, keeping the codebase modular, readable, and easily maintainable across the team.",
  selfCritique:
    "Coming from the JavaScript ecosystem, adopting Dart required higher discipline around static typing and nullability management. Early on, it was tempting to rely on the non-null assertion operator (`!`) or `late` keywords to bypass compiler constraints. I quickly corrected this habit by explicitly modeling variable optionality during initial entity design.",
  hindsight:
    "In hindsight, Dart's syntactic clarity and native AOT compilation make it one of the most reliable client languages available. Writing MyLab's Domain layer in pure Dart remains strong proof that a well-architected codebase transcends UI frameworks and guarantees maximum software stability.",
  evolution:
    "I continue to closely follow Dart language evolutions (notably Dart 3+ features such as Pattern Matching, Records, object destructuring, and `sealed`/`final` class modifiers). I leverage this static typing and object-oriented design rigor daily across all my software engineering projects.",
};
