export const empathyFr = {
  title: "Empathie",
  shortDesc: "Écoute active et compréhension des besoins",
  definition:
    "Pour moi, **l'empathie professionnelle** se définit comme la capacité à percevoir, comprendre et respecter les émotions, les besoins et les contraintes d'autrui, tout en maintenant la distance nécessaire à l'exercice rigoureux de ses fonctions. Elle ne se limite pas à une simple attitude bienveillante, mais constitue un outil d'analyse comportementale permettant de **décoder les signaux** explicites ou implicites d'un interlocuteur.\n\nDans le secteur médico-social, cette compétence est indispensable pour accompagner avec dignité des personnes confrontées à la souffrance physique et morale. Elle exige une **écoute active** et une observation minutieuse pour adapter la prise en charge à des situations individuelles complexes.\n\nDans le domaine du développement logiciel, l'empathie se traduit par ma capacité à **se mettre à la place des clients finaux** pour concevoir des **parcours utilisateurs intuitifs** et accessibles. Elle me permet de comprendre les frustrations et les contraintes opérationnelles du client face à un outil informatique, pour y apporter des réponses fonctionnelles précises.",
  proofs:
    "J'ai développé et exercé cette compétence de manière intensive durant un accompagnement de quatre années auprès d'un usager atteint de la maladie de Charcot, tétraplégique et trachéotomisé. Cet ancien athlète de haut niveau, ayant subi de multiples drames personnels majeurs dont la perte brutale de sa jeune fille, se trouvait dans un état de dépendance physique absolue et ne pouvait communiquer que par le mouvement de ses yeux.\n\nAu début de ma prise en charge, la communication s'avérait extrêmement complexe, l'usager exigeant une précision millimétrée pour des gestes quotidiens comme le positionnement exact de ses membres. Face à sa détresse, il arrivait que l'usager s'exprime de manière très sèche ou agressive en écrivant sur son écran via son système de poursuite oculaire, ou qu'il manifeste son désarroi par des pleurs.\n\nOr, le déclenchement des larmes obstruait la captation de sa caméra oculaire, bloquant instantanément l'ordinateur et provoquant une frustration intense. J'ai pris le temps d'observer ses mimiques pour **anticiper ses besoins** physiques et émotionnels avant que le blocage communicationnel ne survienne. Cette attention de chaque instant m'a permis d'intégrer le cercle très restreint des trois seuls intervenants capables de sécuriser son quotidien.\n\nRécemment, dans mon activité de développeur, j'ai transposé cette sensibilité en me montrant particulièrement **à l'écoute des retours** et des besoins de mes clients lors des phases de test de nos applications. En comprenant finement leurs contraintes et leurs objectifs métier, j'adapte mes développements pour livrer une solution sur mesure conforme à leurs exigences.",
  selfCritique:
    "Cette relation d'aide m'a imposé une **remise en question permanente** face aux réactions émotionnelles de l'usager, en comprenant que ses paroles dures n'étaient pas dirigées contre moi mais exprimaient sa souffrance. J'ai su maintenir la **juste distance professionnelle** tout en faisant preuve d'une grande sensibilité à ses signaux de détresse.\n\nCependant, j'ai dû apprendre à accepter les limites de mon action et à ne pas porter seul la charge émotionnelle de cette situation complexe. Ma décision de l'accompagner durant quatre ans, malgré la difficulté psychologique des interventions, s'est avérée juste et m'a permis de lui offrir un cadre de vie stable.",
  hindsight:
    "Ce suivi au long cours a été l'expérience la plus formatrice de ma carrière sur le plan de la relation humaine et de la connaissance de soi. Le décès de cet usager a été le seul qui m'ait profondément touché, me rappelant que derrière les barrières professionnelles indispensables, l'empathie crée un **lien de confiance inestimable**.\n\nCette épreuve m'a appris à regarder au-delà des apparences et des réactions de surface pour identifier la cause réelle d'un mécontentement ou d'un blocage. L'usager m'encourageait d'ailleurs souvent à progresser par des messages simples d'encouragement, ce qui a ancré en moi une volonté d'amélioration continue.",
  evolution:
    "Pour maintenir et faire évoluer cette compétence, mon objectif est d'appliquer cette même démarche **d'écoute empathique** à l'ensemble de mes projets de développement. Dans mon quotidien, cela se traduit par une collaboration étroite avec les clients pour anticiper leurs difficultés d'appropriation technologique et affiner l'ergonomie de nos solutions.\n\nJe souhaite également soutenir activement mes collègues en étant **attentif aux signes de surcharge ou de stress** au sein de mon équipe projet.",
};

export const empathyEn = {
  title: "Empathy",
  shortDesc: "Active listening and understanding user needs",
  definition:
    "For me, **professional empathy** is defined as the ability to perceive, understand, and respect the emotions, needs, and constraints of others, while maintaining the necessary professional distance to carry out duties rigorously. It is not limited to a benevolent attitude, but constitutes a behavioral analysis tool for **decoding explicit or implicit signals**.\n\nIn healthcare and social work, this skill is essential for supporting individuals facing physical and moral suffering with dignity. It requires **active listening** and meticulous observation to adapt care to complex individual situations.\n\nIn software development, empathy translates to **stepping into end-users' shoes** to design **intuitive** and accessible user journeys, understanding user frustrations to provide precise functional answers.",
  proofs:
    "I developed and exercised this skill intensively during four years supporting an individual with ALS, quadriplegic and tracheostomized. This former high-level athlete had experienced major personal tragedies and communicated solely through eye movements.\n\nInitially, communication was extremely complex. In distress, he expressed frustration sharply via his eye tracker screen or through tears, which obstructed the camera and locked the computer. I observed his expressions to **anticipate needs** before communication breakdowns occurred. This continuous attention granted me entry into the very restricted circle of three caregivers capable of securing his daily life.\n\nRecently, in my developer role, I transposed this sensitivity by being exceptionally **attentive to feedback** and client requirements during testing phases, tailoring developments to deliver bespoke solutions.",
  selfCritique:
    "This helping relationship required **constant self-reflection** regarding emotional reactions, understanding that harsh words were expressions of pain rather than personal attacks. I maintained **appropriate professional distance** while demonstrating deep sensitivity to distress signals.",
  hindsight:
    "Long-term care was the most formative experience of my career regarding human relationships and self-awareness. It taught me to look beyond surface reactions to identify root causes of discontentment or friction.",
  evolution:
    "To maintain and evolve this skill, my goal is to apply this **empathic listening approach** across all software projects, anticipating user adoption hurdles and supporting teammates attentive to stress signals.",
};
