export const javaFr = {
  title: "Java",
  shortDesc: "Langage orienté objet d'entreprise (Spring Boot 3, Hibernate, JPA)",
  definition:
    "Pour moi, **Java** est le langage orienté objet de référence pour construire des architectures serveur d'entreprise robustes, fortement typées et pérennes. Son écosystème, structuré autour de la JVM (Java Virtual Machine) et du framework **Spring Boot 3**, fournit un cadre d'ingénierie rigoureux appliquant les principes de conception (**KISS**, **YAGNI**, **SOLID**, **SOC**).\n\nDans cet écosystème, l'ORM **Hibernate** (implémentation de la norme **JPA** - *Java Persistence API*) simplifie considérablement la couche de données en cartographiant directement les entités Java (`@Entity`, `@Table`) aux tables relationnelles. Associé aux répertoires **Spring Data JPA** (`JpaRepository`), il élimine le code verbeux JDBC tout en préservant la puissance du requêtage SQL.",
  proofs:
    "J'ai mis en pratique Java et Spring Boot à la fois en entreprise, sur des projets personnels et en accompagnement pédagogique :\n\n- **TMA & correctifs en entreprise (Orange Business — Repos Compensateurs)** : En entreprise chez Orange Business, mon intervention sur Java s'est concentrée sur la maintenance corrective et la résolution de bugs sur l'application de **gestion des Repos Compensateurs**, une architecture d'entreprise développée sous **Spring Boot 3** avec Hibernate et JPA.\n\n- **Développement from scratch du projet PMT Back (Projet d'études)** : Pour démontrer ma capacité à concevoir une API REST Java complète from scratch, j'ai développé le dépôt [project-management-tool-back](https://github.com/BuysschaertQuentin/project-management-tool-back). J'y ai mis en place une **architecture en couches stricte** (Contrôleurs `@RestController`, Services métier `@Service`, DataMappers, Repositories `JpaRepository`, DTOs et Entités), qui constitue selon moi la méthode la plus structurée et maintenable pour bâtir un Back-End Java d'entreprise.\n\n- **Transmission pédagogique** : J'enseigne actuellement le développement Java et Spring Boot à l'étudiante que j'accompagne en mentorat, en lui transmettant cette même rigueur d'architecture en couches pour ses projets.\n\n- **Philosophie de sécurité Back-End (Zero Trust)** : Bien que l'exercice académique du projet PMT imposait d'exclure la sécurité sur demande explicite du sujet, je suis en désaccord avec ce principe car **la sécurité est la fondation absolue de tout Back-End**. C'est pourquoi j'accorde une importance centrale à l'enseignement et à la mise en pratique des règles de sécurité basiques : hachage strict des mots de passe (jamais stockés en clair), gestion des tokens JWT via des clés secrètes en variables d'environnement, transmission via cookies sécurisés, et politique **Zero Trust** sur toutes les entrées utilisateurs avec validation systématique des payloads et levée d'exceptions typées.",
  selfCritique:
    "Sur Java, je ne prétends pas posséder l'expertise d'un Lead Dev chevronné, mon expérience en entreprise s'étant limitée à de la TMA sur Spring Boot 3. Cependant, le développement autonome du projet PMT et la transmission pédagogique m'ont permis d'assimiler la structure en couches et d'acquérir de solides bases pour concevoir des APIs REST saines.",
  hindsight:
    "Java et l'écosystème Spring Boot 3 / JPA demeurent une référence majeure sur le marché. Comprendre la séparation des responsabilités entre Entité, DTO et Service est essentiel pour ne jamais exposer directement la base de données au client Front-End.",
  evolution:
    "Java et le framework Spring Boot représentent un langage et un écosystème que j'apprécie énormément. Mon objectif prioritaire pour les prochaines années est de **continuer à développer et approfondir cette compétence**, car c'est **ce que je souhaite pratiquer par la suite** et cela constitue un **pilier central** pour l'évolution de ma stack technique et mon profil de développeur Full-Stack d'entreprise.",
};

export const javaEn = {
  title: "Java",
  shortDesc: "Enterprise object-oriented language (Spring Boot 3, Hibernate, JPA)",
  definition:
    "For me, **Java** is the benchmark object-oriented language for building robust, strongly typed, and sustainable enterprise server architectures. Its ecosystem, structured around the JVM (Java Virtual Machine) and the **Spring Boot 3** framework, delivers a rigorous engineering framework adhering to core design principles (**KISS**, **YAGNI**, **SOLID**, **SOC**).\n\nWithin this ecosystem, the **Hibernate** ORM (implementing the **JPA** standard - *Java Persistence API*) greatly simplifies the data layer by mapping Java entities (`@Entity`, `@Table`) directly to relational tables. Paired with **Spring Data JPA** repositories (`JpaRepository`), it eliminates verbose JDBC code while preserving the power of SQL querying.",
  proofs:
    "I put Java and Spring Boot into practice through enterprise maintenance, personal projects, and educational mentoring:\n\n- **Enterprise Maintenance & Bug Fixing (Orange Business — Compensatory Leave)**: In an enterprise setting at Orange Business, my Java interventions focused on corrective maintenance and bug fixing on the **Compensatory Leave Management** application, an enterprise architecture built with **Spring Boot 3**, Hibernate, and JPA.\n\n- **From-Scratch Development of PMT Back (Academic / Personal Project)**: To prove my capability to architect a complete Java REST API from scratch, I developed the repository [project-management-tool-back](https://github.com/BuysschaertQuentin/project-management-tool-back). I established a **strict layered architecture** (Controllers `@RestController`, Business Services `@Service`, DataMappers, Repositories `JpaRepository`, DTOs, and Entities), which I consider the most structured and maintainable approach for building enterprise Java backends.\n\n- **Educational Mentorship**: I currently teach Java and Spring Boot backend development to the student I mentor, instilling this exact layered architecture rigor for her own projects.\n\n- **Back-End Security Philosophy (Zero Trust)**: Although the PMT academic assignment explicitly requested excluding security, I strongly disagree with that simplification because **security is the foundational baseline of any Back-End**. This is why I place central importance on teaching and practicing core security rules: strict password hashing (never in plain text), JWT token management via secret keys stored in environment variables, transmission via secure HTTP-only cookies, and a strict **Zero Trust policy** on all incoming client payloads with typed exception handling.",
  selfCritique:
    "In Java, I do not claim senior Lead Dev expertise, as my enterprise experience was limited to TMA bug fixing on Spring Boot 3. However, autonomously developing the PMT project and teaching Java to a student enabled me to master layered architecture patterns and acquire solid foundations for designing clean REST APIs.",
  hindsight:
    "Java and the Spring Boot 3 / JPA ecosystem remain a major enterprise benchmark. Understanding the separation of concerns between Entity, DTO, and Service is essential to never expose database structures directly to Front-End clients.",
  evolution:
    "Java and the Spring Boot framework represent a language and ecosystem that I deeply enjoy working with. My primary goal for the coming years is to **continue developing and deepening this skill**, as it is **what I want to focus on going forward** and represents a **central pillar** for the evolution of my technical stack and my profile as an enterprise Full-Stack developer.",
};
