export const resilienceFr = {
  title: "Résilience",
  shortDesc: "Gestion du stress et adaptation",
  definition:
    "Pour moi, la **résilience professionnelle** correspond à la faculté de **maintenir son intégrité opérationnelle, sa lucidité et son efficacité** face à des situations de crise majeure, de stress aigu ou d'imprévus critiques. Elle désigne la capacité à **ne pas se laisser submerger par l'émotion ou la panique** lorsque les circonstances exigent une prise de décision immédiate.\n\nDans le domaine de l'accompagnement à domicile, la résilience se traduit par l'aptitude à gérer des urgences médicales soudaines, où chaque seconde compte, tout en conservant le calme indispensable à l'exécution de gestes complexes. Elle permet de surmonter la charge émotionnelle d'un incident critique pour assurer la continuité des soins et la sécurité de l'usager.\n\nDans le secteur du développement logiciel, cette compétence s'exprime par ma capacité à appréhender les incidents critiques de production, tels que des interruptions de service ou des pertes de données, avec la même rigueur et le même **sang-froid**.",
  proofs:
    "J'ai été confronté à une mise en pratique extrême de cette compétence lors de mon accompagnement à domicile de l'usager atteint de la maladie de Charcot, sous ventilation mécanique par trachéotomie. Durant une séance de soins ordinaires, le ballonnet assurant l'étanchéité et le maintien de la canule trachéale s'est subitement dégonflé, provoquant un appel d'air massif rendant l'assistance respiratoire totalement inefficace.\n\nLe respirateur artificiel s'est mis à émettre des alarmes sonores d'urgence continue, tandis que l'usager, en situation d'asphyxie imminente, manifestait un réflexe de toux violent et m'adressait un regard de détresse absolue. Face à cette situation d'urgence vitale, j'ai dû **surmonter instantanément le stress** pour appliquer le **protocole d'urgence en moins de deux minutes**.\n\nJ'ai débranché les circuits de ventilation, retiré la canule défaillante selon la procédure que le référent infirmier m'avait préalablement montrée à des fins pédagogiques, puis inséré la canule d'urgence de calibre inférieur positionnée à proximité. J'ai ensuite regonflé le ballonnet à l'aide d'une seringue pour rétablir l'étanchéité avant de rebrancher le respirateur, ce qui a immédiatement stabilisé la respiration de l'usager et arrêté les alarmes de la machine.\n\nDans la foulée, j'ai immédiatement prévenu le référent infirmier pour lui détailler mes actions et m'assurer que la situation était sous contrôle. Rassuré par mon rapport, il a écourté ses interventions moins urgentes pour se rendre en priorité chez l'usager. À son arrivée, il a procédé au retrait de la canule d'urgence et à la pose d'une canule standard neuve, une opération délicate que nous avons menée ensemble avec mon assistance technique.",
  selfCritique:
    "L'analyse de cet incident montre que ma réaction a été appropriée et rigoureusement conforme aux protocoles d'urgence que j'avais assimilés. Face à un événement imprévu menaçant directement une vie humaine, céder à la panique aurait été catastrophique pour l'usager.\n\nMa **préparation mentale** et ma connaissance des équipements d'urgence m'ont permis d'agir avec une rapidité et une précision adéquates. J'ai su évaluer la gravité de la situation dès les premiers signaux d'alarme de la machine, sans perdre de temps en diagnostics superflus.",
  hindsight:
    "Cette épreuve a été le test de gestion du stress le plus intense de mon parcours professionnel, et elle a définitivement forgé ma capacité à **relativiser les crises**. En comparaison avec la gestion d'une urgence vitale au domicile d'un patient, les incidents techniques ou les bugs en production logicielle me paraissent beaucoup plus faciles à aborder sereinement.\n\nCette expérience m'a appris qu'une crise ne se résout pas par la précipitation, mais par l'application méthodique de **procédures éprouvées**.",
  evolution:
    "Pour maintenir ce niveau de résilience, je m'efforce de l'appliquer au quotidien dans mon métier de développeur lors de la résolution de dysfonctionnements critiques. Je veille à aborder chaque bug complexe ou chaque retour client difficile comme un problème logique à **résoudre étape par étape**, sans laisser le stress altérer ma réflexion.",
};

export const resilienceEn = {
  title: "Resilience",
  shortDesc: "Stress management and adaptability under pressure",
  definition:
    "For me, **professional resilience** is the ability to **maintain operational integrity, clarity, and effectiveness** in major crisis situations, acute stress, or critical emergencies. It means **not giving in to emotion or panic** when immediate decision-making is required.\n\nIn home care, resilience means managing sudden medical emergencies calmly. In software development, it translates to tackling critical production incidents with composure.",
  proofs:
    "I faced an extreme application when supporting an ALS patient under artificial ventilation. The tracheostomy cuff deflated suddenly, interrupting ventilation. The respirator sounded continuous emergency alarms while the patient choked. I overcame stress to execute the **emergency protocol in under two minutes**.\n\nI disconnected circuits, replaced the faulty tube with a backup smaller tube, reinflated the cuff, and reconnected ventilation—stabilizing his breathing immediately. I then alerted the nurse supervisor who arrived to insert a new standard tube with my assistance.",
  selfCritique:
    "My reaction was strictly compliant with emergency protocols. Mental preparation enabled quick, accurate intervention without wasting time on superfluous diagnostics.",
  hindsight:
    "This was the most intense stress management test of my career. Compared to managing a vital medical emergency at a patient's home, production technical incidents or software bugs appear far easier to handle calmly.",
  evolution:
    "I apply this resilience daily in resolving software incidents, tackling every complex bug step by step without stress altering critical thinking.",
};
