export const sqlFr = {
  title: "SQL",
  shortDesc: "Langage standard de manipulation et de requêtage de bases de données relationnelles",
  definition:
    "Pour moi, **SQL** (Structured Query Language) est le langage universel et incontournable pour interagir avec les bases de données relationnelles. Il permet de structurer les données (DDL - *Data Definition Language*), de les manipuler (DML - *Data Manipulation Language*), de contrôler les accès et de sécuriser les transactions (TCL - *Transaction Control Language*).\n\nAssocier SQL à la conception d'architectures consiste à concevoir des schémas relationnels normalisés (1NF, 2NF, 3NF), à optimiser le coût des requêtes via un indexage intelligent et à déléguer les traitements complexes au moteur de base de données afin de réduire les flux réseau avec le serveur d'application.",
  proofs:
    "J'ai appliqué et approfondi le langage SQL sur l'ensemble de mes projets web et entreprise (O'Voyage, Portail RH, Repos Compensateurs, MyLab) :\n\n- **Vues SQL et extraction CSV (Portail RH chez Orange Business)** : Sur le portail RH, j'ai conçu et créé des **Vues SQL** (`CREATE VIEW`) dédiées. Ces vues permettent de réaliser des jointures complexes entre plusieurs tables d'administration et d'exposer une table virtuelle consolidée, à partir de laquelle le Front-End Angular peut extraire et télécharger directement des synthèses au format CSV pour les besoins métiers.\n\n- **Optimisation des requêtes et indexation B-Tree (O'Voyage)** : Sur le projet *O'Voyage*, j'ai conçu les scripts de migration de base de données. Pour accélérer les jointures sur les clés étrangères volumineuses, j'ai créé des index ciblés (`CREATE INDEX idx_travels ON \"travel\" (\"organizer_id\")` et `idx_activities ON \"activity\" (\"travel_id\")`), réduisant la complexité de recherche de $O(N)$ à $O(\\log N)$.\n\n- **Procédures stockées PL/pgSQL** : Pour exécuter des traitements complexes directement en base et économiser des allers-retours HTTP avec le serveur NestJS, j'ai développé des procédures stockées personnalisées (`get_travelers`, `get_travels`, `get_one_traveler`) prenant en entrée des tableaux d'identifiants (`integer[]`) et retournant des tables typées (`RETURNS TABLE (...)`).\n\n- **Usage d'ORMs (TypeORM & Hibernate / JPA) vs QueryBuilder** :\n  - Sur les projets NestJS (Portail RH), j'utilise **TypeORM**. Lorsque des requêtes nécessitent de manipuler simultanément de multiples critères, je bascule sur le `QueryBuilder` et j'optimise les appels asynchrones concurrents avec `Promise.all()`.\n  - Sur les projets Java (Repos Compensateurs), j'utilise **Hibernate / Spring Data JPA**, la référence d'entreprise qui simplifie grandement les accès données via l'abstraction d'interfaces `JpaRepository`.\n\n- **Gestion des migrations (Sqitch & TypeORM CLI)** : Sur O'Voyage, j'ai géré le versionnement réversible avec **Sqitch** (`BEGIN;` ... `COMMIT;`). Sur le Portail RH avec TypeORM, j'utilise la commande CLI de génération automatique de migrations (`npx typeorm migration:generate src/migrations/MigrationName -d src/data-source.ts`). Je conserve une grande vigilance face à cette génération automatique qui produit parfois du code DDL très volumineux ou verbeux (notamment sur les index et clés étrangères), en nettoyant et repassant manuellement sur le script pour garantir des migrations impeccables.",
  selfCritique:
    "L'utilisation d'ORMs apporte un gain de productivité indéniable, mais elle exige de rester vigilant face aux abstractions. La génération automatique de migrations par TypeORM nécessite une relecture systématique pour éviter d'insérer des contraintes verbeuses ou superflues en base de données. De même, je veille à toujours équilibrer les requêtes entre ORM natif et `QueryBuilder` selon la complexité des jointures.",
  hindsight:
    "Maîtriser le SQL pur en profondeur permet de ne pas subir la magie d'un ORM. Comprendre ce que génère réellement TypeORM ou Hibernate en SQL sous-jacent est la clé absolue pour diagnostiquer les requêtes lentes (problème du N+1 query), concevoir des Vues SQL performantes et maintenir des bases d'entreprise saines.",
  evolution:
    "Je souhaite continuer à approfondir le requêtage SQL avancé (requêtes récursives CTE `WITH RECURSIVE`, fonctions de fenêtrage `OVER (PARTITION BY)` et requêtes d'analyse analytique) pour traiter des volumes de données d'entreprise toujours plus importants.",
};

export const sqlEn = {
  title: "SQL",
  shortDesc: "Standard relational database querying and manipulation language",
  definition:
    "For me, **SQL** (Structured Query Language) is the universal, essential language for interacting with relational database systems. It enables structuring schemas (DDL - *Data Definition Language*), manipulating data (DML - *Data Manipulation Language*), controlling access, and securing transactions (TCL - *Transaction Control Language*).\n\nPairing SQL with sound software engineering involves designing normalized relational models (1NF, 2NF, 3NF), optimizing query execution costs through intelligent indexing, and offloading heavy processing to the database engine to reduce network traffic with application servers.",
  proofs:
    "I applied and deepened standard SQL across all my web and enterprise projects (O'Voyage, HR Portal, Compensatory Leave, MyLab):\n\n- **SQL Views and CSV Export (HR Portal at Orange Business)**: On the HR portal, I designed and created dedicated **SQL Views** (`CREATE VIEW`). These views execute complex multi-table joins across administrative tables, exposing a consolidated virtual table from which the Angular Front-End can extract and download audit summaries directly in CSV format for business needs.\n\n- **Query Optimization and B-Tree Indexing (O'Voyage)**: On *O'Voyage*, I authored database migration scripts. To accelerate joins on large foreign key tables, I created targeted indexes (`CREATE INDEX idx_travels ON \"travel\" (\"organizer_id\")` and `idx_activities ON \"activity\" (\"travel_id\")`), reducing search complexity from $O(N)$ to $O(\\log N)$.\n\n- **Stored Functions and PL/pgSQL Procedures**: To execute complex data queries directly inside the database and eliminate redundant HTTP roundtrips with the NestJS server, I developed custom stored functions (`get_travelers`, `get_travels`, `get_one_traveler`) taking array parameters (`integer[]`) and returning strongly typed result tables (`RETURNS TABLE (...)`).\n\n- **ORM Usage (TypeORM & Hibernate / JPA) vs QueryBuilder**:\n  - On NestJS projects (HR Portal), I use **TypeORM**. When queries require manipulating multiple properties simultaneously, I switch to `QueryBuilder` and optimize concurrent asynchronous execution using `Promise.all()`.\n  - On Java projects (Compensatory Leave), I use **Hibernate / Spring Data JPA**, the enterprise benchmark that greatly simplifies database access via `JpaRepository` interface abstractions.\n\n- **Migration Strategies (Sqitch & TypeORM CLI)**: On O'Voyage, I managed reversible versioning with **Sqitch** (`BEGIN;` ... `COMMIT;`). On the HR Portal with TypeORM, I use the CLI migration generation command (`npx typeorm migration:generate src/migrations/MigrationName -d src/data-source.ts`). I maintain strict vigilance over this automatic generation, which can produce overly verbose DDL code (especially around indexes and foreign keys), double-checking and cleaning scripts manually to ensure flawless migrations.",
  selfCritique:
    "Using ORMs provides indisputable productivity gains, but demands vigilance over generated abstractions. TypeORM's automatic migration generator requires systematic manual review to prevent inserting verbose or superfluous constraints into the database. Similarly, I ensure a proper balance between native ORM methods and `QueryBuilder` based on join complexity.",
  hindsight:
    "Deeply mastering raw SQL prevents relying blindly on ORM abstractions. Understanding the underlying SQL actually executed by TypeORM or Hibernate is the ultimate key for diagnosing slow queries (N+1 query problems), designing performant SQL Views, and maintaining healthy enterprise databases.",
  evolution:
    "I plan to continue deepening my advanced SQL querying skills (recursive CTEs `WITH RECURSIVE`, window functions `OVER (PARTITION BY)`, and analytical queries) to process increasingly large enterprise data volumes effectively.",
};
