export const supabaseFr = {
  title: "Supabase",
  shortDesc: "BaaS (Backend-as-a-Service) open-source basé sur PostgreSQL",
  definition:
    "Pour moi, **Supabase** est la meilleure alternative open-source à Firebase pour construire des architectures d'applications modernes (Mobile et Web). Contrairement aux solutions NoSQL propriétaires, Supabase s'appuie sur la puissance d'une véritable base de données relationnelle **PostgreSQL**.\n\nIl fournit une suite complète de services d'infrastructures prêts à l'emploi : génération automatique d'APIs REST et GraphQL, authentification sécurisée, stockage de fichiers (*Storage buckets*) et sécurité basée sur la politique **Row Level Security (RLS)**. Supabase permet d'accélérer considérablement le développement d'applications sans compromettre la rigueur du modèle relationnel.",
  proofs:
    "J'ai conçu et mis en place l'architecture Back-End sous Supabase pour le projet d'apothéose CDA **MyLab / Compétences** (Web, Android et iOS) chez Orange Business :\n\n- **Le choix de l'économie et de l'open-source** : Pour l'application MyLab, nous envisagions initialement Firebase. S'agissant d'un projet interne sans budget attribué, nous avons fait le choix stratégique d'opter pour **Supabase**. Ce choix nous a permis de bénéficier d'une infrastructure totalement gratuite pour notre volumétrie, sans verrouillage fournisseur (*Vendor Lock-in*), tout en conservant la souplesse d'une base relationnelle SQL.\n\n- **Intégration du SDK Flutter & APIs automatiques** : J'ai connecté l'application mobile et web Flutter à Supabase via le paquet `supabase_flutter`. Supabase a automatiquement généré les endpoints RESTful sécurisés à partir du schéma de tables PostgreSQL, permettant d'exécuter les opérations CRUD (gestion des développeurs, compétences, disponibilités) en temps réel.\n\n- **Sécurité Row Level Security (RLS)** : J'ai rédigé les règles de sécurité **RLS** directement en SQL sous Supabase. Ces politiques garantissent au niveau de la base de données qu'un développeur ne peut modifier que son propre profil et ses propres compétences, tandis que les managers bénéficient d'un accès en lecture élargi sur l'ensemble de l'agence.\n\n- **Gestion du stockage de fichiers (Buckets)** : J'ai configuré les buckets de stockage Supabase pour héberger en toute sécurité les pièces jointes et CVs au format PDF importés par les utilisateurs, avec restriction d'accès par jeton d'authentification.",
  selfCritique:
    "La prise en main de Row Level Security (RLS) exige de la rigueur lors de la rédaction des politiques SQL. Au début du projet, une mauvaise condition dans une politique RLS bloquait l'affichage des requêtes jointes. J'ai corrigé cela en testant méthodiquement chaque rôle utilisateur dans l'interface Supabase Studio.",
  hindsight:
    "Supabase est un outil d'une efficacité redoutable pour réduire le temps de mise sur le marché (*time-to-market*). Il permet de se concentrer sur l'expérience utilisateur et la logique métier de l'application tout en s'appuyant sur la fiabilité d'un moteur PostgreSQL d'entreprise.",
  evolution:
    "Je souhaite continuer à utiliser Supabase sur mes futurs projets Full-Stack et explorer ses fonctionnalités de souscription en temps réel (*Realtime WebSockets*) et d'exécution de code serveur déporté (*Edge Functions*).",
};

export const supabaseEn = {
  title: "Supabase",
  shortDesc: "Open-source BaaS (Backend-as-a-Service) built on PostgreSQL",
  definition:
    "For me, **Supabase** is the premier open-source alternative to Firebase for building modern application architectures (Mobile and Web). Unlike proprietary NoSQL solutions, Supabase leverages the full power of a relational **PostgreSQL** database engine.\n\nIt delivers a complete suite of ready-to-use infrastructure services: automated REST and GraphQL APIs, secure authentication, file storage (*Storage buckets*), and row-level security using **Row Level Security (RLS)** policies. Supabase dramatically accelerates application development without sacrificing relational model integrity.",
  proofs:
    "I designed and deployed the backend architecture on Supabase for the CDA graduation project **MyLab / Skills** (Web, Android, and iOS) at Orange Business:\n\n- **Cost-Effective & Open-Source Choice**: For the MyLab app, we initially considered Firebase. As an internal project with no allocated budget, we made the strategic decision to adopt **Supabase**. This choice allowed us to leverage a completely free infrastructure tier for our volume, avoiding vendor lock-in while preserving relational SQL capabilities.\n\n- **Flutter SDK Integration & Automated APIs**: I connected the Flutter mobile and web apps to Supabase via the `supabase_flutter` package. Supabase automatically generated secure RESTful endpoints from the PostgreSQL table schema, enabling real-time CRUD operations (managing developer profiles, skills, and availability).\n\n- **Row Level Security (RLS)**: I authored **RLS** security rules directly in SQL inside Supabase. These database-level policies guarantee that a developer can only modify their own profile and skills, while resource managers benefit from expanded read access across the agency.\n\n- **File Storage Management (Buckets)**: I configured Supabase Storage buckets to securely host user-uploaded attachments and PDF resumes, restricting access via authentication tokens.",
  selfCritique:
    "Mastering Row Level Security (RLS) requires strict discipline when writing SQL policies. Early in the project, an incorrect RLS condition blocked joined queries. I resolved this by systematically testing each user role within the Supabase Studio dashboard.",
  hindsight:
    "Supabase is an incredibly efficient tool for accelerating time-to-market. It allows developers to focus on application user experience and business logic while relying on the proven stability of an enterprise PostgreSQL engine.",
  evolution:
    "I plan to continue using Supabase on future Full-Stack projects, exploring its real-time WebSocket subscriptions (*Realtime*) and serverless code execution (*Edge Functions*).",
};
