export const vueFr = {
  title: "Vue.js",
  shortDesc: "Framework progressif pour interfaces réactives",
  definition:
    "Pour moi, **Vue.js** est un framework JavaScript progressif et intuitif conçu pour créer des interfaces utilisateur réactives, modulaires et hautement réutilisables. Grâce à son système de réactivité transparent, sa syntaxe de templates expressive et son architecture basée sur les Single File Components (SFC `.vue`), Vue 3 permet d'assembler des applications Web évolutives.\n\nSa flexibilité permet d'évoluer de composants légers jusqu'à des Single Page Applications (SPA) complexes grâce à un écosystème officiel performant (Vue Router, Pinia).",
  proofs:
    "J'ai mis en pratique Vue.js lors de mon **projet de fin d'études DWWM** (Développeur Web et Web Mobile), **O'Voyage** (planificateur collaboratif de voyages). Au sein de l'équipe projet de 5 étudiants (promotion Starship), j'étais initialement affecté au Back-End avec un camarade tandis que 3 étudiants géraient le Front-End (développé au départ sous React/Redux).\n\nAfin de maîtriser la chaîne de développement de bout en bout et de défendre cette compétence avec le plus haut niveau d'exigence et de qualité devant le jury professionnel, j'ai pris l'initiative de **refaire l'intégralité du Front-End en Vue 3** en autonomie, en reprenant tout le processus depuis le cahier des charges, les User Stories, l'arborescence de routes et les wireframes.\n\nSur **O'Voyage**, j'ai conçu une Single Page Application réactive découpée en composants réutilisables spécialisés. J'ai notamment développé un composant générique `Input` réutilisable isolant la validation de formulaires et l'affichage automatique des messages d'erreur via la bibliothèque **Yup** (schémas de validation avec contraintes strictes sur les e-mails et mots de passe, reliés dynamiquement via l'attribut `:name`).\n\nPour optimiser le référencement naturel (SEO) de cette application SPA et corriger les limites de l'indexation client, j'ai intégré la bibliothèque **`@unhead/vue`**, permettant d'injecter dynamiquement des balises `<title>`, `<meta name='description'>` et `<meta name='keywords'>` sur-mesure à chaque changement de route.\n\nEnfin, j'ai apporté un soin particulier à l'accessibilité web (normes WCAG) : structuration sémantique HTML5 complète (`<header>`, `<nav>`, `<main>`, `<article>`, `<aside>`, `<footer>`), hiérarchie stricte des titres (`<h1>`, `<h2>`), ajout systématique d'attributs `aria-label` sur tous les boutons interactifs, attributs `alt` explicites sur les images de voyages, et garantie d'une navigation 100 % au clavier via les touches **Tab** et les flèches directionnelles.",
  selfCritique:
    "Mon choix de reconstruire intégralement le Front-End en Vue.js lors de mon projet de fin d'études était un défi d'autonomie exigeant mais extrêmement gratifiant. Cela m'a permis d'acquérir une véritable polyvalence Full-Stack et de tester l'efficacité de Vue 3 en conditions réelles d'évaluation.",
  hindsight:
    "Vue.js offre une courbe d'apprentissage particulièrement fluide et une lisibilité remarquable du code grâce aux Single File Components. L'utilisation d'outils d'audit comme Google Lighthouse m'a sensibilisé dès mes débuts à l'impact de l'optimisation des visuels et de la structure du DOM sur l'expérience utilisateur globale.",
  evolution:
    "Je n'ai pas eu l'occasion de repratiquer Vue.js depuis ce projet de fin d'études, l'ayant temporairement laissé de côté pour me concentrer intensivement sur l'écosystème Angular en entreprise. Cependant, grâce aux fondamentaux solides acquis et aux similarités conceptuelles (composants, réactivité, routage), cela ne me poserait absolument aucun problème de basculer à nouveau sur des projets en Vue.js si l'opportunité se présentait.",
};

export const vueEn = {
  title: "Vue.js",
  shortDesc: "Progressive framework for reactive interfaces",
  definition:
    "For me, **Vue.js** is an intuitive, progressive JavaScript framework designed for creating reactive, modular, and highly reusable user interfaces. Thanks to its transparent reactivity system, expressive template syntax, and Single File Component (SFC `.vue`) architecture, Vue 3 enables building scalable Web applications.\n\nIts flexibility enables scaling from lightweight components to complex Single Page Applications (SPA) via a high-performing official ecosystem (Vue Router, Pinia).",
  proofs:
    "I put Vue.js into practice on my **DWWM final graduation project** (Web and Mobile Web Developer), **O'Voyage** (a collaborative travel planner). Within the 5-student project team (Starship promo), I was initially assigned to the Back-End alongside a classmate while 3 students managed the Front-End (initially developed in React/Redux).\n\nTo master the entire development pipeline end-to-end and defend this competence with the highest standard of quality before the professional jury, I took the initiative to **rebuild the entire Front-End in Vue 3** autonomously, restarting the process from the requirements document, User Stories, route tree, and wireframes.\n\nOn **O'Voyage**, I designed a reactive Single Page Application partitioned into specialized reusable components. In particular, I developed a generic reusable `Input` component encapsulating form validation and automatic error message rendering via the **Yup** library (validation schemas enforcing strict email and password constraints, dynamically linked via the `:name` attribute).\n\nTo optimize search engine optimization (SEO) on this SPA and overcome client-side indexing limitations, I integrated the **`@unhead/vue`** library, dynamically injecting custom `<title>`, `<meta name='description'>`, and `<meta name='keywords'>` tags on every route change.\n\nFinally, I paid strict attention to web accessibility (WCAG standards): full HTML5 semantic structuring (`<header>`, `<nav>`, `<main>`, `<article>`, `<aside>`, `<footer>`), strict heading hierarchy (`<h1>`, `<h2>`), systematic `aria-label` attributes on all action buttons, explicit `alt` attributes on travel imagery, and 100% keyboard navigation via **Tab** and arrow keys.",
  selfCritique:
    "My decision to rebuild the Front-End in Vue.js for my graduation project was a demanding challenge of individual autonomy and excellence. It enabled me to acquire true Full-Stack versatility and evaluate Vue 3 reactivity under real examination conditions.",
  hindsight:
    "Vue.js delivers a remarkably smooth learning curve and outstanding code readability thanks to Single File Components. Using audit tools like Google Lighthouse early on raised my awareness of how visual optimization and DOM structure directly impact overall user experience.",
  evolution:
    "I have not had the opportunity to practice Vue.js since this graduation project, having set it aside temporarily to focus intensively on the enterprise Angular ecosystem. However, thanks to the solid fundamentals acquired and conceptual similarities (components, reactivity, routing), transitioning back to Vue.js projects would be completely seamless for me if the opportunity arises.",
};
